---
llm_seed: 42
players: 8
humans: 8
map_size: xl
freeform: |
    - the players starting zones need to have WEAK monsters
    - place a choke point in the middle of the map, this zone should be the biggest with the most treasure
    - around it place smaller zones that funnel 2 players each into "ring" mid-fight zone, place some towns here
    - the choke point should be guarded
    - the smaller mid-game zones should be guarded
    - no underground
    - place the player in the maximum distance between one another
