---
llm_seed: 42
players: 8
humans: 4
map_size: m
save_path: $HOME/personal/vcmi-llm-map-generator/dist/momd/
freeform: |
    - no underground
    - use as many custom object as viable to ensure fun gameplay
    - to not spam a specific object type multiple times limit it in zone to 1-3 (or some sane amount)
    - make zones big, rich in treasure
    - other than the starting zones, there is only one big central treasure zone
    - players 1-4 have zones close to one another (1 to 2, 2 to 3, 3 to 4)
    - players 5-8 have zones close to one another (5 to 6, 6 to 7, 7 to 8)
    - zones in (1-4) and (5-8) repel each other
